# Generated by Django 6.0.3 on 2026-03-31 18:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='settings',
            field=models.JSONField(blank=True, default=users.models.default_settings),
        ),
    ]
