# Generated by Django 6.0.3 on 2026-03-31 18:14

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersettings_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
