# Generated by Django 6.1.1 on 2026-09-14 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("group", models.CharField(db_index=True, max_length=40)),
                ("text", models.TextField(help_text="Поддерживает {name}, {date}, {streak}")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("greeting", "Приветствие"),
                            ("holiday", "Праздник"),
                            ("onboarding", "Онбординг"),
                            ("milestone", "Достижение"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "window",
                    models.CharField(
                        choices=[
                            ("popup", "Всплывающее окно"),
                            ("string", "Строка на странице"),
                            ("modal", "Модалка"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Один раз за всё время"),
                            ("daily", "Раз в день"),
                            ("weekly", "Раз в неделю"),
                            ("monthly", "Раз в месяц"),
                            ("yearly", "Раз в год"),
                            ("condition", "По условию (без периода)"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(default=100, help_text="Меньше — важнее"),
                ),
                (
                    "condition_key",
                    models.CharField(
                        blank=True,
                        help_text="Имя функции из announcements/conditions.py",
                        max_length=50,
                    ),
                ),
                ("condition_params", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("priority", "code"),
                "indexes": [
                    models.Index(
                        fields=["active", "priority"], name="announcemen_active_cd28a8_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementShown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("group", models.CharField(max_length=40)),
                ("period_key", models.CharField(max_length=20)),
                ("shown_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "group", "period_key"), name="unique_group_per_user_period"
                    )
                ],
            },
        ),
    ]
