# Generated by Django 6.0.3 on 2026-05-23 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('user', 'Дейстивя пользователя'), ('admin', 'Действия администратора'), ('system', 'Системное действие')], max_length=10)),
                ('action', models.CharField(choices=[('ban', 'Блокировка'), ('unban', 'Разблокировка'), ('ownership_transfer', 'Передача прав владельца'), ('send_telegram', 'Рассылка в Telegram'), ('send_email', 'Рассылка Email'), ('appeal_approved', 'Апелляция одобрена'), ('appeal_rejected', 'Апелляция отклонена'), ('login', 'Вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход'), ('register', 'Регистрация'), ('password_change', 'Смена пароля'), ('email_change', 'Смена email'), ('username_change', 'Смена username'), ('telegram_connect', 'Подключение Telegram'), ('telegram_disconnect', 'Отключение Telegram'), ('avatar_upload', 'Загрузка аватара'), ('auto_unban', 'Авторазблокировка')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['performed_by', '-created_at'], name='audit_audit_perform_aa8f00_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
