# Generated by Django 6.0.3 on 2026-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ban', 'Блокировка'), ('unban', 'Разблокировка'), ('ownership_transfer', 'Передача прав владельца'), ('send_telegram', 'Рассылка в Telegram'), ('send_email', 'Рассылка Email'), ('appeal_approved', 'Апелляция одобрена'), ('appeal_rejected', 'Апелляция отклонена'), ('login', 'Вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход'), ('register', 'Регистрация'), ('password_change', 'Смена пароля'), ('email_change', 'Смена email'), ('name_change', 'Смена имени'), ('username_change', 'Смена username'), ('telegram_connect', 'Подключение Telegram'), ('telegram_disconnect', 'Отключение Telegram'), ('avatar_upload', 'Загрузка аватара'), ('delete_account', 'Удаление аккаунта'), ('auto_unban', 'Авторазблокировка')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('user', 'Действия пользователя'), ('admin', 'Действия администратора'), ('system', 'Системное действие')], max_length=10),
        ),
    ]
