# Generated by Django 6.1.1 on 2026-09-22 17:20

import instavault.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=instavault.apps.users.models.avatar_upload_to),
        ),
    ]
