# Generated by Django 6.1.1 on 2026-09-08 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='planner.habit'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='planner.tasktemplate'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_active'], name='habit_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', 'date'], name='habit_comp_habit_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitcompletion',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_completion_per_date'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['user', 'is_active'], name='task_template_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'date'], name='task_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'date', 'completed'], name='task_user_date_completed_idx'),
        ),
    ]
