# Generated by Django 6.0.3 on 2026-04-01 15:03

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Главный суперадмин'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='settings',
            field=models.JSONField(blank=True, default=users.models.default_settings, verbose_name='настройки'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['telegram_id'], name='users_custo_telegra_366165_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_owner'], name='users_custo_is_owne_6af42f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='users_custo_is_acti_1b62ea_idx'),
        ),
    ]
