# Generated by Django 6.0.3 on 2026-05-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_customuser_options_customuser_is_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ended_ban',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец блокировки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reason_ban',
            field=models.CharField(blank=True, max_length=500, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='started_ban',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало блокировки'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['ended_ban'], name='users_custo_ended_b_61a27f_idx'),
        ),
    ]
