# Generated by Django 6.0.3 on 2026-05-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_ended_ban_customuser_reason_ban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Апелляция',
                'verbose_name_plural': 'Апелляции',
                'ordering': ['-created_at'],
            },
        ),
    ]
