# Generated by Django 6.1.1 on 2026-09-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('user', 'Действия пользователя'), ('admin', 'Действия администратора'), ('system', 'Системное действие')], max_length=10)),
                ('action', models.CharField(choices=[('ban', 'Блокировка'), ('unban', 'Разблокировка'), ('ownership_transfer', 'Передача прав владельца'), ('send_telegram', 'Рассылка в Telegram'), ('send_email', 'Рассылка Email'), ('appeal_approved', 'Апелляция одобрена'), ('appeal_rejected', 'Апелляция отклонена'), ('login', 'Вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход'), ('register', 'Регистрация'), ('password_change', 'Смена пароля'), ('email_change', 'Смена email'), ('name_change', 'Смена имени'), ('username_change', 'Смена username'), ('telegram_connect', 'Подключение Telegram'), ('telegram_disconnect', 'Отключение Telegram'), ('avatar_upload', 'Загрузка аватара'), ('delete_account', 'Удаление аккаунта'), ('auto_unban', 'Авторазблокировка')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ('-created_at',),
            },
        ),
    ]
